version: '3'
services:
  web:
    image: nginx
    links:
      - reactapp
    ports:
      - "${SYMFONY_NGINX_PORT}:80"
    environment:
      - NGINX_HOST=${SYMFONY_NGINX_HOST}
      - NGINX_PORT=${SYMFONY_NGINX_PORT}
    volumes:
      - ./:/var/www/symfony:cached
      - ./app/config/nginx/conf.d/site.dev.conf:/etc/nginx/conf.d/site.template:ro
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  phpapp:
    image: php:7.1-fpm
    working_dir: /var/www/symfony
    user: www-data
    volumes:
      - ./:/var/www/symfony:cached
      - ./var/logs/:/var/www/symfony/var/logs:cached
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${SYMFONY_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SYMFONY_MYSQL_DATABASE}
      MYSQL_USER: ${SYMFONY_MYSQL_USER}
      MYSQL_PASSWORD: ${SYMFONY_MYSQL_PASSWORD}
  reactapp:
    image: node:latest
    environment:
      - NPM_CONFIG_LOGLEVEL=warn
      - NODE_ENV=dev
    user: node
    command: bash -c "yarn install --pure-lockfile && yarn start"
    working_dir: /home/node/app/frontend
    volumes:
      - ./:/home/node/app

volumes:
  code:
