version: '3'
services:
  web:
    image: nginx
    ports:
      - "${SYMFONY_NGINX_PORT}:80"
    environment:
      - NGINX_HOST=${SYMFONY_NGINX_HOST}
      - NGINX_PORT=${SYMFONY_NGINX_PORT}
    volumes:
      - ./:/var/www/symfony:cached
      - ./app/config/nginx/conf.d/site.dev.conf:/etc/nginx/conf.d/site.template
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  phpfpm:
    image: php:7.1-fpm
    volumes:
      - ./:/var/www/symfony:cached
      - ./var/logs/:/var/www/symfony/var/logs:cached
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${SYMFONY_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SYMFONY_MYSQL_DATABASE}
      MYSQL_USER: ${SYMFONY_MYSQL_USER}
      MYSQL_PASSWORD: ${SYMFONY_MYSQL_PASSWORD}

volumes:
  code:
